version: '3'

services:
  backend:
    image: 686226086270.dkr.ecr.us-east-1.amazonaws.com/accenture-microservices-demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: accenture-microservices-demo
        awslogs-region: us-east-1
        awslogs-stream-prefix: backend
