version: '3'

services:
  backend:
    image: localhost:5000/accenture-microservices-demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
